- ignore: {name: Use if}
- ignore: {name: Use tan, within: NumHask.Algebra.Field}
- ignore: {name: Use logBase, within: NumHask.Algebra.Field}
- ignore: {name: Use -}
- ignore: {name: Eta reduce}
- ignore: {name: Redundant lambda, within: NumHask.Hedgehog.Prop}
- ignore: {name: Reduce duplication, within: NumHask.Hedgehog.Prop}
- ignore: {name: Redundant lambda, within: NumHask.Hedgehog.Prop.Space}
- ignore: {name: Reduce duplication, within: NumHask.Hedgehog.Prop.Space}
- ignore: {name: Redundant fromInteger}
