resolver: nightly-2020-06-25

packages:
  - numhask
  - numhask-prelude
  - numhask-hedgehog

extra-deps:
  - protolude-0.3.0
  - git: https://github.com/tonyday567/numhask-space
    commit: b559c42cc43de8b837721861f5e02ef8bba9e6ee
